### ISSUE TITLE
Viewer cant open raw datasets

### ISSUE THREAD

**Issue by rajramasawmy** [ismrmrd/ismrmrdviewer#9]
I can open image h5 datasets, but viewer throws this error for the test raw datasets:

objc[37132]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9b082cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11544ccd8). One of the two will be used. Which one is undefined.
[INFO] Opening file: __installpath__/ismrmrdviewer/res/data/simple.h5
Traceback (most recent call last):
  File "__installpath__/ismrmrdviewer/venv/lib/python3.6/site-packages/ismrmrdviewer-0.1.0-py3.6.egg/ismrmrdviewer/ui/MainWindow.py", line 43, in open_file
  File "__installpath__/ismrmrdviewer/venv/lib/python3.6/site-packages/ismrmrdviewer-0.1.0-py3.6.egg/ismrmrdviewer/ui/FileWidget.py", line 19, in __init__
  File "__installpath__/ismrmrdviewer/venv/lib/python3.6/site-packages/ismrmrd/file.py", line 353, in __init__
    self.__file = h5py.File(filename, mode)
  File "__installpath__/ismrmrdviewer/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "__installpath__/ismrmrdviewer/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

// --------------------------------------------------
This is running macOS, with the following setup.
>> git clone https://github.com/ismrmrd/ismrmrdviewer.git
>> cd ismrmrdviewer/
>> python3 -m venv venv
>> . venv/bin/activate
>> python3 setup.py --verbose install
>> ismrmrdviewer

**Comment by rajramasawmy** [comment]
Problem solved...
Need to manually download the test datasets from github! Git clone doesn't pull the whole file.
